"""Add tags to questions

Revision ID: 111212ff1cba
Revises: b53b1ff06244
Create Date: 2016-05-09 22:40:50.187634

"""

# revision identifiers, used by Alembic.
revision = '111212ff1cba'
down_revision = 'b53b1ff06244'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag_name', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag_name')
    )
    op.create_table('tags_questions',
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.alter_column(u'questions', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'questions', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('tags_questions')
    op.drop_table('tags')
    ### end Alembic commands ###
