"""Add timestamp to questions

Revision ID: b53b1ff06244
Revises: 806df343f343
Create Date: 2016-04-14 13:16:34.756406

"""

# revision identifiers, used by Alembic.
revision = 'b53b1ff06244'
down_revision = '806df343f343'

from alembic import op
from sqlalchemy import func
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('timestamp', sa.DateTime(), server_default=func.now(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'timestamp')
    ### end Alembic commands ###
